// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: worker.proto

package worker_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistRequest) Reset() {
	*x = RegistRequest{}
	mi := &file_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistRequest) ProtoMessage() {}

func (x *RegistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistRequest.ProtoReflect.Descriptor instead.
func (*RegistRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{0}
}

func (x *RegistRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegistRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistResponse) Reset() {
	*x = RegistResponse{}
	mi := &file_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistResponse) ProtoMessage() {}

func (x *RegistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistResponse.ProtoReflect.Descriptor instead.
func (*RegistResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{1}
}

func (x *RegistResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegistResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskType      int32                  `protobuf:"varint,1,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	TaskLevel     int32                  `protobuf:"varint,2,opt,name=task_level,json=taskLevel,proto3" json:"task_level,omitempty"`
	TaskPriority  int32                  `protobuf:"varint,3,opt,name=task_priority,json=taskPriority,proto3" json:"task_priority,omitempty"`
	DecodeType    int32                  `protobuf:"varint,4,opt,name=decode_type,json=decodeType,proto3" json:"decode_type,omitempty"`
	TaskData      []byte                 `protobuf:"bytes,5,opt,name=task_data,json=taskData,proto3" json:"task_data,omitempty"`
	Success       bool                   `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{2}
}

func (x *Task) GetTaskType() int32 {
	if x != nil {
		return x.TaskType
	}
	return 0
}

func (x *Task) GetTaskLevel() int32 {
	if x != nil {
		return x.TaskLevel
	}
	return 0
}

func (x *Task) GetTaskPriority() int32 {
	if x != nil {
		return x.TaskPriority
	}
	return 0
}

func (x *Task) GetDecodeType() int32 {
	if x != nil {
		return x.DecodeType
	}
	return 0
}

func (x *Task) GetTaskData() []byte {
	if x != nil {
		return x.TaskData
	}
	return nil
}

func (x *Task) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// status: "0:undo", "1:in_progress", "2:completed", "3:some_failed", "4:all_failed"
type TaskReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Detail        []*Task                `protobuf:"bytes,3,rep,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskReportRequest) Reset() {
	*x = TaskReportRequest{}
	mi := &file_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskReportRequest) ProtoMessage() {}

func (x *TaskReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskReportRequest.ProtoReflect.Descriptor instead.
func (*TaskReportRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{3}
}

func (x *TaskReportRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskReportRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TaskReportRequest) GetDetail() []*Task {
	if x != nil {
		return x.Detail
	}
	return nil
}

type TaskDistribution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskDistribution) Reset() {
	*x = TaskDistribution{}
	mi := &file_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskDistribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDistribution) ProtoMessage() {}

func (x *TaskDistribution) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDistribution.ProtoReflect.Descriptor instead.
func (*TaskDistribution) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{4}
}

func (x *TaskDistribution) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskDistribution) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TaskReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	Tasks         []*TaskDistribution    `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskReportResponse) Reset() {
	*x = TaskReportResponse{}
	mi := &file_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskReportResponse) ProtoMessage() {}

func (x *TaskReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskReportResponse.ProtoReflect.Descriptor instead.
func (*TaskReportResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{5}
}

func (x *TaskReportResponse) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

func (x *TaskReportResponse) GetTasks() []*TaskDistribution {
	if x != nil {
		return x.Tasks
	}
	return nil
}

var File_worker_proto protoreflect.FileDescriptor

const file_worker_proto_rawDesc = "" +
	"\n" +
	"\fworker.proto\x12\x0eworker_service\"H\n" +
	"\rRegistRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"B\n" +
	"\x0eRegistResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\"\xbf\x01\n" +
	"\x04Task\x12\x1b\n" +
	"\ttask_type\x18\x01 \x01(\x05R\btaskType\x12\x1d\n" +
	"\n" +
	"task_level\x18\x02 \x01(\x05R\ttaskLevel\x12#\n" +
	"\rtask_priority\x18\x03 \x01(\x05R\ftaskPriority\x12\x1f\n" +
	"\vdecode_type\x18\x04 \x01(\x05R\n" +
	"decodeType\x12\x1b\n" +
	"\ttask_data\x18\x05 \x01(\fR\btaskData\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\bR\asuccess\"r\n" +
	"\x11TaskReportRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12,\n" +
	"\x06detail\x18\x03 \x03(\v2\x14.worker_service.TaskR\x06detail\"H\n" +
	"\x10TaskDistribution\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\"h\n" +
	"\x12TaskReportResponse\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived\x126\n" +
	"\x05tasks\x18\x02 \x03(\v2 .worker_service.TaskDistributionR\x05tasks2\xbd\x01\n" +
	"\x11Worker2Controller\x12M\n" +
	"\fRegistWorker\x12\x1d.worker_service.RegistRequest\x1a\x1e.worker_service.RegistResponse\x12Y\n" +
	"\x10ReportTaskStatus\x12!.worker_service.TaskReportRequest\x1a\".worker_service.TaskReportResponseB)Z'script/rpc_server/worker;worker_serviceb\x06proto3"

var (
	file_worker_proto_rawDescOnce sync.Once
	file_worker_proto_rawDescData []byte
)

func file_worker_proto_rawDescGZIP() []byte {
	file_worker_proto_rawDescOnce.Do(func() {
		file_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)))
	})
	return file_worker_proto_rawDescData
}

var file_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_worker_proto_goTypes = []any{
	(*RegistRequest)(nil),      // 0: worker_service.RegistRequest
	(*RegistResponse)(nil),     // 1: worker_service.RegistResponse
	(*Task)(nil),               // 2: worker_service.Task
	(*TaskReportRequest)(nil),  // 3: worker_service.TaskReportRequest
	(*TaskDistribution)(nil),   // 4: worker_service.TaskDistribution
	(*TaskReportResponse)(nil), // 5: worker_service.TaskReportResponse
}
var file_worker_proto_depIdxs = []int32{
	2, // 0: worker_service.TaskReportRequest.detail:type_name -> worker_service.Task
	4, // 1: worker_service.TaskReportResponse.tasks:type_name -> worker_service.TaskDistribution
	0, // 2: worker_service.Worker2Controller.RegistWorker:input_type -> worker_service.RegistRequest
	3, // 3: worker_service.Worker2Controller.ReportTaskStatus:input_type -> worker_service.TaskReportRequest
	1, // 4: worker_service.Worker2Controller.RegistWorker:output_type -> worker_service.RegistResponse
	5, // 5: worker_service.Worker2Controller.ReportTaskStatus:output_type -> worker_service.TaskReportResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_worker_proto_init() }
func file_worker_proto_init() {
	if File_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_proto_goTypes,
		DependencyIndexes: file_worker_proto_depIdxs,
		MessageInfos:      file_worker_proto_msgTypes,
	}.Build()
	File_worker_proto = out.File
	file_worker_proto_goTypes = nil
	file_worker_proto_depIdxs = nil
}
