// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: worker.proto

package worker_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Worker2Controller_RegistWorker_FullMethodName     = "/worker_service.Worker2Controller/RegistWorker"
	Worker2Controller_ReportTaskStatus_FullMethodName = "/worker_service.Worker2Controller/ReportTaskStatus"
)

// Worker2ControllerClient is the client API for Worker2Controller service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Worker2ControllerClient interface {
	RegistWorker(ctx context.Context, in *RegistRequest, opts ...grpc.CallOption) (*RegistResponse, error)
	ReportTaskStatus(ctx context.Context, in *TaskReportRequest, opts ...grpc.CallOption) (*TaskReportResponse, error)
}

type worker2ControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewWorker2ControllerClient(cc grpc.ClientConnInterface) Worker2ControllerClient {
	return &worker2ControllerClient{cc}
}

func (c *worker2ControllerClient) RegistWorker(ctx context.Context, in *RegistRequest, opts ...grpc.CallOption) (*RegistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistResponse)
	err := c.cc.Invoke(ctx, Worker2Controller_RegistWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worker2ControllerClient) ReportTaskStatus(ctx context.Context, in *TaskReportRequest, opts ...grpc.CallOption) (*TaskReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskReportResponse)
	err := c.cc.Invoke(ctx, Worker2Controller_ReportTaskStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Worker2ControllerServer is the server API for Worker2Controller service.
// All implementations must embed UnimplementedWorker2ControllerServer
// for forward compatibility.
type Worker2ControllerServer interface {
	RegistWorker(context.Context, *RegistRequest) (*RegistResponse, error)
	ReportTaskStatus(context.Context, *TaskReportRequest) (*TaskReportResponse, error)
	mustEmbedUnimplementedWorker2ControllerServer()
}

// UnimplementedWorker2ControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorker2ControllerServer struct{}

func (UnimplementedWorker2ControllerServer) RegistWorker(context.Context, *RegistRequest) (*RegistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegistWorker not implemented")
}
func (UnimplementedWorker2ControllerServer) ReportTaskStatus(context.Context, *TaskReportRequest) (*TaskReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportTaskStatus not implemented")
}
func (UnimplementedWorker2ControllerServer) mustEmbedUnimplementedWorker2ControllerServer() {}
func (UnimplementedWorker2ControllerServer) testEmbeddedByValue()                           {}

// UnsafeWorker2ControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Worker2ControllerServer will
// result in compilation errors.
type UnsafeWorker2ControllerServer interface {
	mustEmbedUnimplementedWorker2ControllerServer()
}

func RegisterWorker2ControllerServer(s grpc.ServiceRegistrar, srv Worker2ControllerServer) {
	// If the following call pancis, it indicates UnimplementedWorker2ControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Worker2Controller_ServiceDesc, srv)
}

func _Worker2Controller_RegistWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Worker2ControllerServer).RegistWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker2Controller_RegistWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Worker2ControllerServer).RegistWorker(ctx, req.(*RegistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker2Controller_ReportTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Worker2ControllerServer).ReportTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker2Controller_ReportTaskStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Worker2ControllerServer).ReportTaskStatus(ctx, req.(*TaskReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Worker2Controller_ServiceDesc is the grpc.ServiceDesc for Worker2Controller service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Worker2Controller_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "worker_service.Worker2Controller",
	HandlerType: (*Worker2ControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegistWorker",
			Handler:    _Worker2Controller_RegistWorker_Handler,
		},
		{
			MethodName: "ReportTaskStatus",
			Handler:    _Worker2Controller_ReportTaskStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "worker.proto",
}
