// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: worker.proto

package worker_2_controller_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Info          *WorkerInfo            `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistRequest) Reset() {
	*x = RegistRequest{}
	mi := &file_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistRequest) ProtoMessage() {}

func (x *RegistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistRequest.ProtoReflect.Descriptor instead.
func (*RegistRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{0}
}

func (x *RegistRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RegistRequest) GetInfo() *WorkerInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type WorkerInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Host
	Hostname        string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os              string `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Platform        string `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformVersion string `protobuf:"bytes,4,opt,name=platform_version,json=platformVersion,proto3" json:"platform_version,omitempty"`
	KernelVersion   string `protobuf:"bytes,5,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	Arch            string `protobuf:"bytes,6,opt,name=arch,proto3" json:"arch,omitempty"`
	// CPU
	CpuLogicalCores  int32  `protobuf:"varint,8,opt,name=cpu_logical_cores,json=cpuLogicalCores,proto3" json:"cpu_logical_cores,omitempty"`
	CpuPhysicalCores int32  `protobuf:"varint,9,opt,name=cpu_physical_cores,json=cpuPhysicalCores,proto3" json:"cpu_physical_cores,omitempty"`
	CpuModelName     string `protobuf:"bytes,10,opt,name=cpu_model_name,json=cpuModelName,proto3" json:"cpu_model_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WorkerInfo) Reset() {
	*x = WorkerInfo{}
	mi := &file_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerInfo) ProtoMessage() {}

func (x *WorkerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerInfo.ProtoReflect.Descriptor instead.
func (*WorkerInfo) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *WorkerInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *WorkerInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *WorkerInfo) GetPlatformVersion() string {
	if x != nil {
		return x.PlatformVersion
	}
	return ""
}

func (x *WorkerInfo) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *WorkerInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *WorkerInfo) GetCpuLogicalCores() int32 {
	if x != nil {
		return x.CpuLogicalCores
	}
	return 0
}

func (x *WorkerInfo) GetCpuPhysicalCores() int32 {
	if x != nil {
		return x.CpuPhysicalCores
	}
	return 0
}

func (x *WorkerInfo) GetCpuModelName() string {
	if x != nil {
		return x.CpuModelName
	}
	return ""
}

type RegistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistResponse) Reset() {
	*x = RegistResponse{}
	mi := &file_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistResponse) ProtoMessage() {}

func (x *RegistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistResponse.ProtoReflect.Descriptor instead.
func (*RegistResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{2}
}

func (x *RegistResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegistResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskType      int32                  `protobuf:"varint,1,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	TaskLevel     int32                  `protobuf:"varint,2,opt,name=task_level,json=taskLevel,proto3" json:"task_level,omitempty"`
	TaskPriority  int32                  `protobuf:"varint,3,opt,name=task_priority,json=taskPriority,proto3" json:"task_priority,omitempty"`
	TaskData      []byte                 `protobuf:"bytes,4,opt,name=task_data,json=taskData,proto3" json:"task_data,omitempty"`
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{3}
}

func (x *Task) GetTaskType() int32 {
	if x != nil {
		return x.TaskType
	}
	return 0
}

func (x *Task) GetTaskLevel() int32 {
	if x != nil {
		return x.TaskLevel
	}
	return 0
}

func (x *Task) GetTaskPriority() int32 {
	if x != nil {
		return x.TaskPriority
	}
	return 0
}

func (x *Task) GetTaskData() []byte {
	if x != nil {
		return x.TaskData
	}
	return nil
}

func (x *Task) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TaskReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskPortId    string                 `protobuf:"bytes,1,opt,name=task_port_id,json=taskPortId,proto3" json:"task_port_id,omitempty"`
	Details       []*Task                `protobuf:"bytes,2,rep,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskReportRequest) Reset() {
	*x = TaskReportRequest{}
	mi := &file_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskReportRequest) ProtoMessage() {}

func (x *TaskReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskReportRequest.ProtoReflect.Descriptor instead.
func (*TaskReportRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{4}
}

func (x *TaskReportRequest) GetTaskPortId() string {
	if x != nil {
		return x.TaskPortId
	}
	return ""
}

func (x *TaskReportRequest) GetDetails() []*Task {
	if x != nil {
		return x.Details
	}
	return nil
}

type TaskDistribution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskDistribution) Reset() {
	*x = TaskDistribution{}
	mi := &file_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskDistribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDistribution) ProtoMessage() {}

func (x *TaskDistribution) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDistribution.ProtoReflect.Descriptor instead.
func (*TaskDistribution) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{5}
}

func (x *TaskDistribution) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskDistribution) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TaskReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	Tasks         []*TaskDistribution    `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskReportResponse) Reset() {
	*x = TaskReportResponse{}
	mi := &file_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskReportResponse) ProtoMessage() {}

func (x *TaskReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskReportResponse.ProtoReflect.Descriptor instead.
func (*TaskReportResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{6}
}

func (x *TaskReportResponse) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

func (x *TaskReportResponse) GetTasks() []*TaskDistribution {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type CpuInfo struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	CpuLogicalCores       int32                  `protobuf:"varint,1,opt,name=cpu_logical_cores,json=cpuLogicalCores,proto3" json:"cpu_logical_cores,omitempty"`
	SuperThreadingEnabled bool                   `protobuf:"varint,2,opt,name=super_threading_enabled,json=superThreadingEnabled,proto3" json:"super_threading_enabled,omitempty"`
	CpuUsagePercents      []float64              `protobuf:"fixed64,3,rep,packed,name=cpu_usage_percents,json=cpuUsagePercents,proto3" json:"cpu_usage_percents,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CpuInfo) Reset() {
	*x = CpuInfo{}
	mi := &file_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuInfo) ProtoMessage() {}

func (x *CpuInfo) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuInfo.ProtoReflect.Descriptor instead.
func (*CpuInfo) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{7}
}

func (x *CpuInfo) GetCpuLogicalCores() int32 {
	if x != nil {
		return x.CpuLogicalCores
	}
	return 0
}

func (x *CpuInfo) GetSuperThreadingEnabled() bool {
	if x != nil {
		return x.SuperThreadingEnabled
	}
	return false
}

func (x *CpuInfo) GetCpuUsagePercents() []float64 {
	if x != nil {
		return x.CpuUsagePercents
	}
	return nil
}

type MemoryInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MemoryUsagePercent float64                `protobuf:"fixed64,1,opt,name=memory_usage_percent,json=memoryUsagePercent,proto3" json:"memory_usage_percent,omitempty"`
	MemoryTotal        uint64                 `protobuf:"varint,2,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MemoryInfo) Reset() {
	*x = MemoryInfo{}
	mi := &file_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryInfo) ProtoMessage() {}

func (x *MemoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryInfo.ProtoReflect.Descriptor instead.
func (*MemoryInfo) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{8}
}

func (x *MemoryInfo) GetMemoryUsagePercent() float64 {
	if x != nil {
		return x.MemoryUsagePercent
	}
	return 0
}

func (x *MemoryInfo) GetMemoryTotal() uint64 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

type DiskInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DiskUsagePercent float64                `protobuf:"fixed64,1,opt,name=disk_usage_percent,json=diskUsagePercent,proto3" json:"disk_usage_percent,omitempty"`
	DiskTotal        uint64                 `protobuf:"varint,2,opt,name=disk_total,json=diskTotal,proto3" json:"disk_total,omitempty"`
	DiskReadBytes    int32                  `protobuf:"varint,3,opt,name=disk_read_bytes,json=diskReadBytes,proto3" json:"disk_read_bytes,omitempty"`
	DiskWriteBytes   int32                  `protobuf:"varint,4,opt,name=disk_write_bytes,json=diskWriteBytes,proto3" json:"disk_write_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DiskInfo) Reset() {
	*x = DiskInfo{}
	mi := &file_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskInfo) ProtoMessage() {}

func (x *DiskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskInfo.ProtoReflect.Descriptor instead.
func (*DiskInfo) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{9}
}

func (x *DiskInfo) GetDiskUsagePercent() float64 {
	if x != nil {
		return x.DiskUsagePercent
	}
	return 0
}

func (x *DiskInfo) GetDiskTotal() uint64 {
	if x != nil {
		return x.DiskTotal
	}
	return 0
}

func (x *DiskInfo) GetDiskReadBytes() int32 {
	if x != nil {
		return x.DiskReadBytes
	}
	return 0
}

func (x *DiskInfo) GetDiskWriteBytes() int32 {
	if x != nil {
		return x.DiskWriteBytes
	}
	return 0
}

type NetworkInfo struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	InterfaceName        string                 `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	NetworkSentBytes     int32                  `protobuf:"varint,2,opt,name=network_sent_bytes,json=networkSentBytes,proto3" json:"network_sent_bytes,omitempty"`
	NetworkReceivedBytes int32                  `protobuf:"varint,3,opt,name=network_received_bytes,json=networkReceivedBytes,proto3" json:"network_received_bytes,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NetworkInfo) Reset() {
	*x = NetworkInfo{}
	mi := &file_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInfo) ProtoMessage() {}

func (x *NetworkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInfo.ProtoReflect.Descriptor instead.
func (*NetworkInfo) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{10}
}

func (x *NetworkInfo) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *NetworkInfo) GetNetworkSentBytes() int32 {
	if x != nil {
		return x.NetworkSentBytes
	}
	return 0
}

func (x *NetworkInfo) GetNetworkReceivedBytes() int32 {
	if x != nil {
		return x.NetworkReceivedBytes
	}
	return 0
}

type Status struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CPU
	Cpu *CpuInfo `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	// Memory
	Memory *MemoryInfo `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	// Disk
	Disk *DiskInfo `protobuf:"bytes,3,opt,name=disk,proto3" json:"disk,omitempty"`
	// Network
	Network *NetworkInfo `protobuf:"bytes,4,opt,name=network,proto3" json:"network,omitempty"`
	// App
	TaskCount     int32 `protobuf:"varint,5,opt,name=task_count,json=taskCount,proto3" json:"task_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_worker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{11}
}

func (x *Status) GetCpu() *CpuInfo {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *Status) GetMemory() *MemoryInfo {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *Status) GetDisk() *DiskInfo {
	if x != nil {
		return x.Disk
	}
	return nil
}

func (x *Status) GetNetwork() *NetworkInfo {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *Status) GetTaskCount() int32 {
	if x != nil {
		return x.TaskCount
	}
	return 0
}

type RepeatedStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*Status              `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatedStatus) Reset() {
	*x = RepeatedStatus{}
	mi := &file_worker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatedStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedStatus) ProtoMessage() {}

func (x *RepeatedStatus) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedStatus.ProtoReflect.Descriptor instead.
func (*RepeatedStatus) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{12}
}

func (x *RepeatedStatus) GetStatuses() []*Status {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type HeartingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	Status        *Status                `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartingRequest) Reset() {
	*x = HeartingRequest{}
	mi := &file_worker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartingRequest) ProtoMessage() {}

func (x *HeartingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartingRequest.ProtoReflect.Descriptor instead.
func (*HeartingRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{13}
}

func (x *HeartingRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *HeartingRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *HeartingRequest) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type HeartingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartingResponse) Reset() {
	*x = HeartingResponse{}
	mi := &file_worker_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartingResponse) ProtoMessage() {}

func (x *HeartingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartingResponse.ProtoReflect.Descriptor instead.
func (*HeartingResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{14}
}

func (x *HeartingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_worker_proto protoreflect.FileDescriptor

const file_worker_proto_rawDesc = "" +
	"\n" +
	"\fworker.proto\x12\x1bworker_2_controller_service\"\\\n" +
	"\rRegistRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12;\n" +
	"\x04info\x18\x02 \x01(\v2'.worker_2_controller_service.WorkerInfoR\x04info\"\xba\x02\n" +
	"\n" +
	"WorkerInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12)\n" +
	"\x10platform_version\x18\x04 \x01(\tR\x0fplatformVersion\x12%\n" +
	"\x0ekernel_version\x18\x05 \x01(\tR\rkernelVersion\x12\x12\n" +
	"\x04arch\x18\x06 \x01(\tR\x04arch\x12*\n" +
	"\x11cpu_logical_cores\x18\b \x01(\x05R\x0fcpuLogicalCores\x12,\n" +
	"\x12cpu_physical_cores\x18\t \x01(\x05R\x10cpuPhysicalCores\x12$\n" +
	"\x0ecpu_model_name\x18\n" +
	" \x01(\tR\fcpuModelName\"B\n" +
	"\x0eRegistResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\"\x9e\x01\n" +
	"\x04Task\x12\x1b\n" +
	"\ttask_type\x18\x01 \x01(\x05R\btaskType\x12\x1d\n" +
	"\n" +
	"task_level\x18\x02 \x01(\x05R\ttaskLevel\x12#\n" +
	"\rtask_priority\x18\x03 \x01(\x05R\ftaskPriority\x12\x1b\n" +
	"\ttask_data\x18\x04 \x01(\fR\btaskData\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\"r\n" +
	"\x11TaskReportRequest\x12 \n" +
	"\ftask_port_id\x18\x01 \x01(\tR\n" +
	"taskPortId\x12;\n" +
	"\adetails\x18\x02 \x03(\v2!.worker_2_controller_service.TaskR\adetails\"H\n" +
	"\x10TaskDistribution\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\"u\n" +
	"\x12TaskReportResponse\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived\x12C\n" +
	"\x05tasks\x18\x02 \x03(\v2-.worker_2_controller_service.TaskDistributionR\x05tasks\"\x9b\x01\n" +
	"\aCpuInfo\x12*\n" +
	"\x11cpu_logical_cores\x18\x01 \x01(\x05R\x0fcpuLogicalCores\x126\n" +
	"\x17super_threading_enabled\x18\x02 \x01(\bR\x15superThreadingEnabled\x12,\n" +
	"\x12cpu_usage_percents\x18\x03 \x03(\x01R\x10cpuUsagePercents\"a\n" +
	"\n" +
	"MemoryInfo\x120\n" +
	"\x14memory_usage_percent\x18\x01 \x01(\x01R\x12memoryUsagePercent\x12!\n" +
	"\fmemory_total\x18\x02 \x01(\x04R\vmemoryTotal\"\xa9\x01\n" +
	"\bDiskInfo\x12,\n" +
	"\x12disk_usage_percent\x18\x01 \x01(\x01R\x10diskUsagePercent\x12\x1d\n" +
	"\n" +
	"disk_total\x18\x02 \x01(\x04R\tdiskTotal\x12&\n" +
	"\x0fdisk_read_bytes\x18\x03 \x01(\x05R\rdiskReadBytes\x12(\n" +
	"\x10disk_write_bytes\x18\x04 \x01(\x05R\x0ediskWriteBytes\"\x98\x01\n" +
	"\vNetworkInfo\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\x12,\n" +
	"\x12network_sent_bytes\x18\x02 \x01(\x05R\x10networkSentBytes\x124\n" +
	"\x16network_received_bytes\x18\x03 \x01(\x05R\x14networkReceivedBytes\"\x9f\x02\n" +
	"\x06Status\x126\n" +
	"\x03cpu\x18\x01 \x01(\v2$.worker_2_controller_service.CpuInfoR\x03cpu\x12?\n" +
	"\x06memory\x18\x02 \x01(\v2'.worker_2_controller_service.MemoryInfoR\x06memory\x129\n" +
	"\x04disk\x18\x03 \x01(\v2%.worker_2_controller_service.DiskInfoR\x04disk\x12B\n" +
	"\anetwork\x18\x04 \x01(\v2(.worker_2_controller_service.NetworkInfoR\anetwork\x12\x1d\n" +
	"\n" +
	"task_count\x18\x05 \x01(\x05R\ttaskCount\"Q\n" +
	"\x0eRepeatedStatus\x12?\n" +
	"\bstatuses\x18\x01 \x03(\v2#.worker_2_controller_service.StatusR\bstatuses\"v\n" +
	"\x0fHeartingRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12;\n" +
	"\x06status\x18\x03 \x01(\v2#.worker_2_controller_service.StatusR\x06status\",\n" +
	"\x10HeartingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xda\x02\n" +
	"\x11Worker2Controller\x12g\n" +
	"\fRegistWorker\x12*.worker_2_controller_service.RegistRequest\x1a+.worker_2_controller_service.RegistResponse\x12g\n" +
	"\bHearting\x12,.worker_2_controller_service.HeartingRequest\x1a-.worker_2_controller_service.HeartingResponse\x12s\n" +
	"\x10ReportTaskStatus\x12..worker_2_controller_service.TaskReportRequest\x1a/.worker_2_controller_service.TaskReportResponseB6Z4script/rpc_server/worker;worker_2_controller_serviceb\x06proto3"

var (
	file_worker_proto_rawDescOnce sync.Once
	file_worker_proto_rawDescData []byte
)

func file_worker_proto_rawDescGZIP() []byte {
	file_worker_proto_rawDescOnce.Do(func() {
		file_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)))
	})
	return file_worker_proto_rawDescData
}

var file_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_worker_proto_goTypes = []any{
	(*RegistRequest)(nil),      // 0: worker_2_controller_service.RegistRequest
	(*WorkerInfo)(nil),         // 1: worker_2_controller_service.WorkerInfo
	(*RegistResponse)(nil),     // 2: worker_2_controller_service.RegistResponse
	(*Task)(nil),               // 3: worker_2_controller_service.Task
	(*TaskReportRequest)(nil),  // 4: worker_2_controller_service.TaskReportRequest
	(*TaskDistribution)(nil),   // 5: worker_2_controller_service.TaskDistribution
	(*TaskReportResponse)(nil), // 6: worker_2_controller_service.TaskReportResponse
	(*CpuInfo)(nil),            // 7: worker_2_controller_service.CpuInfo
	(*MemoryInfo)(nil),         // 8: worker_2_controller_service.MemoryInfo
	(*DiskInfo)(nil),           // 9: worker_2_controller_service.DiskInfo
	(*NetworkInfo)(nil),        // 10: worker_2_controller_service.NetworkInfo
	(*Status)(nil),             // 11: worker_2_controller_service.Status
	(*RepeatedStatus)(nil),     // 12: worker_2_controller_service.RepeatedStatus
	(*HeartingRequest)(nil),    // 13: worker_2_controller_service.HeartingRequest
	(*HeartingResponse)(nil),   // 14: worker_2_controller_service.HeartingResponse
}
var file_worker_proto_depIdxs = []int32{
	1,  // 0: worker_2_controller_service.RegistRequest.info:type_name -> worker_2_controller_service.WorkerInfo
	3,  // 1: worker_2_controller_service.TaskReportRequest.details:type_name -> worker_2_controller_service.Task
	5,  // 2: worker_2_controller_service.TaskReportResponse.tasks:type_name -> worker_2_controller_service.TaskDistribution
	7,  // 3: worker_2_controller_service.Status.cpu:type_name -> worker_2_controller_service.CpuInfo
	8,  // 4: worker_2_controller_service.Status.memory:type_name -> worker_2_controller_service.MemoryInfo
	9,  // 5: worker_2_controller_service.Status.disk:type_name -> worker_2_controller_service.DiskInfo
	10, // 6: worker_2_controller_service.Status.network:type_name -> worker_2_controller_service.NetworkInfo
	11, // 7: worker_2_controller_service.RepeatedStatus.statuses:type_name -> worker_2_controller_service.Status
	11, // 8: worker_2_controller_service.HeartingRequest.status:type_name -> worker_2_controller_service.Status
	0,  // 9: worker_2_controller_service.Worker2Controller.RegistWorker:input_type -> worker_2_controller_service.RegistRequest
	13, // 10: worker_2_controller_service.Worker2Controller.Hearting:input_type -> worker_2_controller_service.HeartingRequest
	4,  // 11: worker_2_controller_service.Worker2Controller.ReportTaskStatus:input_type -> worker_2_controller_service.TaskReportRequest
	2,  // 12: worker_2_controller_service.Worker2Controller.RegistWorker:output_type -> worker_2_controller_service.RegistResponse
	14, // 13: worker_2_controller_service.Worker2Controller.Hearting:output_type -> worker_2_controller_service.HeartingResponse
	6,  // 14: worker_2_controller_service.Worker2Controller.ReportTaskStatus:output_type -> worker_2_controller_service.TaskReportResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_worker_proto_init() }
func file_worker_proto_init() {
	if File_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_proto_goTypes,
		DependencyIndexes: file_worker_proto_depIdxs,
		MessageInfos:      file_worker_proto_msgTypes,
	}.Build()
	File_worker_proto = out.File
	file_worker_proto_goTypes = nil
	file_worker_proto_depIdxs = nil
}
