// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: brander.proto

package brander_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeartingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartingRequest) Reset() {
	*x = HeartingRequest{}
	mi := &file_brander_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartingRequest) ProtoMessage() {}

func (x *HeartingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brander_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartingRequest.ProtoReflect.Descriptor instead.
func (*HeartingRequest) Descriptor() ([]byte, []int) {
	return file_brander_proto_rawDescGZIP(), []int{0}
}

func (x *HeartingRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type MachineStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage      float32                `protobuf:"fixed32,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	CpuCores      int32                  `protobuf:"varint,2,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	CpuFrequency  float32                `protobuf:"fixed32,3,opt,name=cpu_frequency,json=cpuFrequency,proto3" json:"cpu_frequency,omitempty"`
	MemoryUsage   float32                `protobuf:"fixed32,4,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	MemoryTotal   float32                `protobuf:"fixed32,5,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	TaskCount     int32                  `protobuf:"varint,6,opt,name=task_count,json=taskCount,proto3" json:"task_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineStatusResponse) Reset() {
	*x = MachineStatusResponse{}
	mi := &file_brander_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineStatusResponse) ProtoMessage() {}

func (x *MachineStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brander_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineStatusResponse.ProtoReflect.Descriptor instead.
func (*MachineStatusResponse) Descriptor() ([]byte, []int) {
	return file_brander_proto_rawDescGZIP(), []int{1}
}

func (x *MachineStatusResponse) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *MachineStatusResponse) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *MachineStatusResponse) GetCpuFrequency() float32 {
	if x != nil {
		return x.CpuFrequency
	}
	return 0
}

func (x *MachineStatusResponse) GetMemoryUsage() float32 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *MachineStatusResponse) GetMemoryTotal() float32 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

func (x *MachineStatusResponse) GetTaskCount() int32 {
	if x != nil {
		return x.TaskCount
	}
	return 0
}

var File_brander_proto protoreflect.FileDescriptor

const file_brander_proto_rawDesc = "" +
	"\n" +
	"\rbrander.proto\x12\abrander\"!\n" +
	"\x0fHeartingRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"\xdb\x01\n" +
	"\x15MachineStatusResponse\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x02R\bcpuUsage\x12\x1b\n" +
	"\tcpu_cores\x18\x02 \x01(\x05R\bcpuCores\x12#\n" +
	"\rcpu_frequency\x18\x03 \x01(\x02R\fcpuFrequency\x12!\n" +
	"\fmemory_usage\x18\x04 \x01(\x02R\vmemoryUsage\x12!\n" +
	"\fmemory_total\x18\x05 \x01(\x02R\vmemoryTotal\x12\x1d\n" +
	"\n" +
	"task_count\x18\x06 \x01(\x05R\ttaskCount2[\n" +
	"\x13BranderWorkerStatus\x12D\n" +
	"\bHearting\x12\x18.brander.HeartingRequest\x1a\x1e.brander.MachineStatusResponseB+Z)script/rpc_server/brander;brander_serviceb\x06proto3"

var (
	file_brander_proto_rawDescOnce sync.Once
	file_brander_proto_rawDescData []byte
)

func file_brander_proto_rawDescGZIP() []byte {
	file_brander_proto_rawDescOnce.Do(func() {
		file_brander_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_brander_proto_rawDesc), len(file_brander_proto_rawDesc)))
	})
	return file_brander_proto_rawDescData
}

var file_brander_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_brander_proto_goTypes = []any{
	(*HeartingRequest)(nil),       // 0: brander.HeartingRequest
	(*MachineStatusResponse)(nil), // 1: brander.MachineStatusResponse
}
var file_brander_proto_depIdxs = []int32{
	0, // 0: brander.BranderWorkerStatus.Hearting:input_type -> brander.HeartingRequest
	1, // 1: brander.BranderWorkerStatus.Hearting:output_type -> brander.MachineStatusResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_brander_proto_init() }
func file_brander_proto_init() {
	if File_brander_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_brander_proto_rawDesc), len(file_brander_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_brander_proto_goTypes,
		DependencyIndexes: file_brander_proto_depIdxs,
		MessageInfos:      file_brander_proto_msgTypes,
	}.Build()
	File_brander_proto = out.File
	file_brander_proto_goTypes = nil
	file_brander_proto_depIdxs = nil
}
