// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: brander.proto

package brander_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BranderWorkerStatus_Hearting_FullMethodName = "/brander.BranderWorkerStatus/Hearting"
)

// BranderWorkerStatusClient is the client API for BranderWorkerStatus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BranderWorkerStatusClient interface {
	Hearting(ctx context.Context, in *HeartingRequest, opts ...grpc.CallOption) (*MachineStatusResponse, error)
}

type branderWorkerStatusClient struct {
	cc grpc.ClientConnInterface
}

func NewBranderWorkerStatusClient(cc grpc.ClientConnInterface) BranderWorkerStatusClient {
	return &branderWorkerStatusClient{cc}
}

func (c *branderWorkerStatusClient) Hearting(ctx context.Context, in *HeartingRequest, opts ...grpc.CallOption) (*MachineStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MachineStatusResponse)
	err := c.cc.Invoke(ctx, BranderWorkerStatus_Hearting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BranderWorkerStatusServer is the server API for BranderWorkerStatus service.
// All implementations must embed UnimplementedBranderWorkerStatusServer
// for forward compatibility.
type BranderWorkerStatusServer interface {
	Hearting(context.Context, *HeartingRequest) (*MachineStatusResponse, error)
	mustEmbedUnimplementedBranderWorkerStatusServer()
}

// UnimplementedBranderWorkerStatusServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBranderWorkerStatusServer struct{}

func (UnimplementedBranderWorkerStatusServer) Hearting(context.Context, *HeartingRequest) (*MachineStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hearting not implemented")
}
func (UnimplementedBranderWorkerStatusServer) mustEmbedUnimplementedBranderWorkerStatusServer() {}
func (UnimplementedBranderWorkerStatusServer) testEmbeddedByValue()                             {}

// UnsafeBranderWorkerStatusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BranderWorkerStatusServer will
// result in compilation errors.
type UnsafeBranderWorkerStatusServer interface {
	mustEmbedUnimplementedBranderWorkerStatusServer()
}

func RegisterBranderWorkerStatusServer(s grpc.ServiceRegistrar, srv BranderWorkerStatusServer) {
	// If the following call pancis, it indicates UnimplementedBranderWorkerStatusServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BranderWorkerStatus_ServiceDesc, srv)
}

func _BranderWorkerStatus_Hearting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BranderWorkerStatusServer).Hearting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BranderWorkerStatus_Hearting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BranderWorkerStatusServer).Hearting(ctx, req.(*HeartingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BranderWorkerStatus_ServiceDesc is the grpc.ServiceDesc for BranderWorkerStatus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BranderWorkerStatus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "brander.BranderWorkerStatus",
	HandlerType: (*BranderWorkerStatusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hearting",
			Handler:    _BranderWorkerStatus_Hearting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "brander.proto",
}
