// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: controller.proto

package controller_2_worker_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Controller2Worker_DispatchTask_FullMethodName   = "/controller_2_worker_service.Controller2Worker/DispatchTask"
	Controller2Worker_CancelTask_FullMethodName     = "/controller_2_worker_service.Controller2Worker/CancelTask"
	Controller2Worker_Ping_FullMethodName           = "/controller_2_worker_service.Controller2Worker/Ping"
	Controller2Worker_ReportProgress_FullMethodName = "/controller_2_worker_service.Controller2Worker/ReportProgress"
	Controller2Worker_ListTasks_FullMethodName      = "/controller_2_worker_service.Controller2Worker/ListTasks"
)

// Controller2WorkerClient is the client API for Controller2Worker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Controller2WorkerClient interface {
	// 下发任务分片到 worker
	DispatchTask(ctx context.Context, in *DispatchTaskRequest, opts ...grpc.CallOption) (*DispatchTaskResponse, error)
	// 取消正在执行的任务
	CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error)
	// controller 主动 ping worker（探活 + 延迟测量）
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// worker 上报任务进度（单次调用，worker 定期调用）
	ReportProgress(ctx context.Context, in *TaskProgressReport, opts ...grpc.CallOption) (*TaskProgressResponse, error)
	// 查询 worker 上当前所有任务
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
}

type controller2WorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewController2WorkerClient(cc grpc.ClientConnInterface) Controller2WorkerClient {
	return &controller2WorkerClient{cc}
}

func (c *controller2WorkerClient) DispatchTask(ctx context.Context, in *DispatchTaskRequest, opts ...grpc.CallOption) (*DispatchTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatchTaskResponse)
	err := c.cc.Invoke(ctx, Controller2Worker_DispatchTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controller2WorkerClient) CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTaskResponse)
	err := c.cc.Invoke(ctx, Controller2Worker_CancelTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controller2WorkerClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, Controller2Worker_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controller2WorkerClient) ReportProgress(ctx context.Context, in *TaskProgressReport, opts ...grpc.CallOption) (*TaskProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskProgressResponse)
	err := c.cc.Invoke(ctx, Controller2Worker_ReportProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controller2WorkerClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, Controller2Worker_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Controller2WorkerServer is the server API for Controller2Worker service.
// All implementations must embed UnimplementedController2WorkerServer
// for forward compatibility.
type Controller2WorkerServer interface {
	// 下发任务分片到 worker
	DispatchTask(context.Context, *DispatchTaskRequest) (*DispatchTaskResponse, error)
	// 取消正在执行的任务
	CancelTask(context.Context, *CancelTaskRequest) (*CancelTaskResponse, error)
	// controller 主动 ping worker（探活 + 延迟测量）
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// worker 上报任务进度（单次调用，worker 定期调用）
	ReportProgress(context.Context, *TaskProgressReport) (*TaskProgressResponse, error)
	// 查询 worker 上当前所有任务
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	mustEmbedUnimplementedController2WorkerServer()
}

// UnimplementedController2WorkerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedController2WorkerServer struct{}

func (UnimplementedController2WorkerServer) DispatchTask(context.Context, *DispatchTaskRequest) (*DispatchTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DispatchTask not implemented")
}
func (UnimplementedController2WorkerServer) CancelTask(context.Context, *CancelTaskRequest) (*CancelTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTask not implemented")
}
func (UnimplementedController2WorkerServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedController2WorkerServer) ReportProgress(context.Context, *TaskProgressReport) (*TaskProgressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportProgress not implemented")
}
func (UnimplementedController2WorkerServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedController2WorkerServer) mustEmbedUnimplementedController2WorkerServer() {}
func (UnimplementedController2WorkerServer) testEmbeddedByValue()                           {}

// UnsafeController2WorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Controller2WorkerServer will
// result in compilation errors.
type UnsafeController2WorkerServer interface {
	mustEmbedUnimplementedController2WorkerServer()
}

func RegisterController2WorkerServer(s grpc.ServiceRegistrar, srv Controller2WorkerServer) {
	// If the following call panics, it indicates UnimplementedController2WorkerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Controller2Worker_ServiceDesc, srv)
}

func _Controller2Worker_DispatchTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Controller2WorkerServer).DispatchTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller2Worker_DispatchTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Controller2WorkerServer).DispatchTask(ctx, req.(*DispatchTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller2Worker_CancelTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Controller2WorkerServer).CancelTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller2Worker_CancelTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Controller2WorkerServer).CancelTask(ctx, req.(*CancelTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller2Worker_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Controller2WorkerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller2Worker_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Controller2WorkerServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller2Worker_ReportProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskProgressReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Controller2WorkerServer).ReportProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller2Worker_ReportProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Controller2WorkerServer).ReportProgress(ctx, req.(*TaskProgressReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller2Worker_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Controller2WorkerServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller2Worker_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Controller2WorkerServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Controller2Worker_ServiceDesc is the grpc.ServiceDesc for Controller2Worker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Controller2Worker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "controller_2_worker_service.Controller2Worker",
	HandlerType: (*Controller2WorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DispatchTask",
			Handler:    _Controller2Worker_DispatchTask_Handler,
		},
		{
			MethodName: "CancelTask",
			Handler:    _Controller2Worker_CancelTask_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Controller2Worker_Ping_Handler,
		},
		{
			MethodName: "ReportProgress",
			Handler:    _Controller2Worker_ReportProgress_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _Controller2Worker_ListTasks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controller.proto",
}
