// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: controller.proto

package controller_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage      float32                `protobuf:"fixed32,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	CpuCores      int32                  `protobuf:"varint,2,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	CpuFrequency  float32                `protobuf:"fixed32,3,opt,name=cpu_frequency,json=cpuFrequency,proto3" json:"cpu_frequency,omitempty"`
	MemoryUsage   float32                `protobuf:"fixed32,4,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	MemoryTotal   float32                `protobuf:"fixed32,5,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	TaskCount     int32                  `protobuf:"varint,6,opt,name=task_count,json=taskCount,proto3" json:"task_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_controller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *Status) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *Status) GetCpuFrequency() float32 {
	if x != nil {
		return x.CpuFrequency
	}
	return 0
}

func (x *Status) GetMemoryUsage() float32 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *Status) GetMemoryTotal() float32 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

func (x *Status) GetTaskCount() int32 {
	if x != nil {
		return x.TaskCount
	}
	return 0
}

type HeartingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Status        *Status                `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartingRequest) Reset() {
	*x = HeartingRequest{}
	mi := &file_controller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartingRequest) ProtoMessage() {}

func (x *HeartingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartingRequest.ProtoReflect.Descriptor instead.
func (*HeartingRequest) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{1}
}

func (x *HeartingRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *HeartingRequest) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type HeartingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartingResponse) Reset() {
	*x = HeartingResponse{}
	mi := &file_controller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartingResponse) ProtoMessage() {}

func (x *HeartingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartingResponse.ProtoReflect.Descriptor instead.
func (*HeartingResponse) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{2}
}

var File_controller_proto protoreflect.FileDescriptor

const file_controller_proto_rawDesc = "" +
	"\n" +
	"\x10controller.proto\x12\x12controller_service\"\xcc\x01\n" +
	"\x06Status\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x02R\bcpuUsage\x12\x1b\n" +
	"\tcpu_cores\x18\x02 \x01(\x05R\bcpuCores\x12#\n" +
	"\rcpu_frequency\x18\x03 \x01(\x02R\fcpuFrequency\x12!\n" +
	"\fmemory_usage\x18\x04 \x01(\x02R\vmemoryUsage\x12!\n" +
	"\fmemory_total\x18\x05 \x01(\x02R\vmemoryTotal\x12\x1d\n" +
	"\n" +
	"task_count\x18\x06 \x01(\x05R\ttaskCount\"U\n" +
	"\x0fHeartingRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x122\n" +
	"\x06status\x18\x02 \x01(\v2\x1a.controller_service.StatusR\x06status\"\x12\n" +
	"\x10HeartingResponse2l\n" +
	"\x13BranderWorkerStatus\x12U\n" +
	"\bHearting\x12#.controller_service.HeartingRequest\x1a$.controller_service.HeartingResponseB1Z/script/rpc_server/controller;controller_serviceb\x06proto3"

var (
	file_controller_proto_rawDescOnce sync.Once
	file_controller_proto_rawDescData []byte
)

func file_controller_proto_rawDescGZIP() []byte {
	file_controller_proto_rawDescOnce.Do(func() {
		file_controller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controller_proto_rawDesc), len(file_controller_proto_rawDesc)))
	})
	return file_controller_proto_rawDescData
}

var file_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_controller_proto_goTypes = []any{
	(*Status)(nil),           // 0: controller_service.Status
	(*HeartingRequest)(nil),  // 1: controller_service.HeartingRequest
	(*HeartingResponse)(nil), // 2: controller_service.HeartingResponse
}
var file_controller_proto_depIdxs = []int32{
	0, // 0: controller_service.HeartingRequest.status:type_name -> controller_service.Status
	1, // 1: controller_service.BranderWorkerStatus.Hearting:input_type -> controller_service.HeartingRequest
	2, // 2: controller_service.BranderWorkerStatus.Hearting:output_type -> controller_service.HeartingResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_controller_proto_init() }
func file_controller_proto_init() {
	if File_controller_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controller_proto_rawDesc), len(file_controller_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controller_proto_goTypes,
		DependencyIndexes: file_controller_proto_depIdxs,
		MessageInfos:      file_controller_proto_msgTypes,
	}.Build()
	File_controller_proto = out.File
	file_controller_proto_goTypes = nil
	file_controller_proto_depIdxs = nil
}
