// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: controller.proto

package controller_2_worker_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskType      int32                  `protobuf:"varint,1,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	TaskLevel     int32                  `protobuf:"varint,2,opt,name=task_level,json=taskLevel,proto3" json:"task_level,omitempty"`
	TaskPriority  int32                  `protobuf:"varint,3,opt,name=task_priority,json=taskPriority,proto3" json:"task_priority,omitempty"`
	TaskData      []byte                 `protobuf:"bytes,4,opt,name=task_data,json=taskData,proto3" json:"task_data,omitempty"`
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_controller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetTaskType() int32 {
	if x != nil {
		return x.TaskType
	}
	return 0
}

func (x *Task) GetTaskLevel() int32 {
	if x != nil {
		return x.TaskLevel
	}
	return 0
}

func (x *Task) GetTaskPriority() int32 {
	if x != nil {
		return x.TaskPriority
	}
	return 0
}

func (x *Task) GetTaskData() []byte {
	if x != nil {
		return x.TaskData
	}
	return nil
}

func (x *Task) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TaskReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskPortId    string                 `protobuf:"bytes,1,opt,name=task_port_id,json=taskPortId,proto3" json:"task_port_id,omitempty"`
	Details       []*Task                `protobuf:"bytes,2,rep,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskReportRequest) Reset() {
	*x = TaskReportRequest{}
	mi := &file_controller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskReportRequest) ProtoMessage() {}

func (x *TaskReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskReportRequest.ProtoReflect.Descriptor instead.
func (*TaskReportRequest) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{1}
}

func (x *TaskReportRequest) GetTaskPortId() string {
	if x != nil {
		return x.TaskPortId
	}
	return ""
}

func (x *TaskReportRequest) GetDetails() []*Task {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_controller_proto protoreflect.FileDescriptor

const file_controller_proto_rawDesc = "" +
	"\n" +
	"\x10controller.proto\x12\x1bcontroller_2_worker_service\"\x9e\x01\n" +
	"\x04Task\x12\x1b\n" +
	"\ttask_type\x18\x01 \x01(\x05R\btaskType\x12\x1d\n" +
	"\n" +
	"task_level\x18\x02 \x01(\x05R\ttaskLevel\x12#\n" +
	"\rtask_priority\x18\x03 \x01(\x05R\ftaskPriority\x12\x1b\n" +
	"\ttask_data\x18\x04 \x01(\fR\btaskData\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\"r\n" +
	"\x11TaskReportRequest\x12 \n" +
	"\ftask_port_id\x18\x01 \x01(\tR\n" +
	"taskPortId\x12;\n" +
	"\adetails\x18\x02 \x03(\v2!.controller_2_worker_service.TaskR\adetailsB:Z8script/rpc_server/controller;controller_2_worker_serviceb\x06proto3"

var (
	file_controller_proto_rawDescOnce sync.Once
	file_controller_proto_rawDescData []byte
)

func file_controller_proto_rawDescGZIP() []byte {
	file_controller_proto_rawDescOnce.Do(func() {
		file_controller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controller_proto_rawDesc), len(file_controller_proto_rawDesc)))
	})
	return file_controller_proto_rawDescData
}

var file_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_controller_proto_goTypes = []any{
	(*Task)(nil),              // 0: controller_2_worker_service.Task
	(*TaskReportRequest)(nil), // 1: controller_2_worker_service.TaskReportRequest
}
var file_controller_proto_depIdxs = []int32{
	0, // 0: controller_2_worker_service.TaskReportRequest.details:type_name -> controller_2_worker_service.Task
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_controller_proto_init() }
func file_controller_proto_init() {
	if File_controller_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controller_proto_rawDesc), len(file_controller_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_controller_proto_goTypes,
		DependencyIndexes: file_controller_proto_depIdxs,
		MessageInfos:      file_controller_proto_msgTypes,
	}.Build()
	File_controller_proto = out.File
	file_controller_proto_goTypes = nil
	file_controller_proto_depIdxs = nil
}
