// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: controller.proto

package controller_2_worker_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 任务状态枚举
type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNKNOWN   TaskStatus = 0
	TaskStatus_TASK_STATUS_PENDING   TaskStatus = 1 // 已接收，等待执行
	TaskStatus_TASK_STATUS_RUNNING   TaskStatus = 2 // 正在执行
	TaskStatus_TASK_STATUS_COMPLETED TaskStatus = 3 // 执行完成
	TaskStatus_TASK_STATUS_FAILED    TaskStatus = 4 // 执行失败
	TaskStatus_TASK_STATUS_CANCELLED TaskStatus = 5 // 已取消
	TaskStatus_TASK_STATUS_TIMEOUT   TaskStatus = 6 // 超时
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNKNOWN",
		1: "TASK_STATUS_PENDING",
		2: "TASK_STATUS_RUNNING",
		3: "TASK_STATUS_COMPLETED",
		4: "TASK_STATUS_FAILED",
		5: "TASK_STATUS_CANCELLED",
		6: "TASK_STATUS_TIMEOUT",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNKNOWN":   0,
		"TASK_STATUS_PENDING":   1,
		"TASK_STATUS_RUNNING":   2,
		"TASK_STATUS_COMPLETED": 3,
		"TASK_STATUS_FAILED":    4,
		"TASK_STATUS_CANCELLED": 5,
		"TASK_STATUS_TIMEOUT":   6,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_controller_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_controller_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{0}
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskType      int32                  `protobuf:"varint,1,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	TaskLevel     int32                  `protobuf:"varint,2,opt,name=task_level,json=taskLevel,proto3" json:"task_level,omitempty"`
	TaskPriority  int32                  `protobuf:"varint,3,opt,name=task_priority,json=taskPriority,proto3" json:"task_priority,omitempty"`
	TaskData      []byte                 `protobuf:"bytes,4,opt,name=task_data,json=taskData,proto3" json:"task_data,omitempty"`
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_controller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetTaskType() int32 {
	if x != nil {
		return x.TaskType
	}
	return 0
}

func (x *Task) GetTaskLevel() int32 {
	if x != nil {
		return x.TaskLevel
	}
	return 0
}

func (x *Task) GetTaskPriority() int32 {
	if x != nil {
		return x.TaskPriority
	}
	return 0
}

func (x *Task) GetTaskData() []byte {
	if x != nil {
		return x.TaskData
	}
	return nil
}

func (x *Task) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TaskReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskPortId    string                 `protobuf:"bytes,1,opt,name=task_port_id,json=taskPortId,proto3" json:"task_port_id,omitempty"`
	Details       []*Task                `protobuf:"bytes,2,rep,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskReportRequest) Reset() {
	*x = TaskReportRequest{}
	mi := &file_controller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskReportRequest) ProtoMessage() {}

func (x *TaskReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskReportRequest.ProtoReflect.Descriptor instead.
func (*TaskReportRequest) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{1}
}

func (x *TaskReportRequest) GetTaskPortId() string {
	if x != nil {
		return x.TaskPortId
	}
	return ""
}

func (x *TaskReportRequest) GetDetails() []*Task {
	if x != nil {
		return x.Details
	}
	return nil
}

// 任务分片描述（由 scheduler.SplitTask 生成）
type TaskChunk struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	TaskId       string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                     // 全局唯一任务 ID
	ParentTaskId string                 `protobuf:"bytes,2,opt,name=parent_task_id,json=parentTaskId,proto3" json:"parent_task_id,omitempty"` // 父任务 ID（拆分前的原始任务）
	ChunkIndex   int32                  `protobuf:"varint,3,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`        // 分片索引（从 0 开始）
	TotalChunks  int32                  `protobuf:"varint,4,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`     // 总分片数
	// 任务类型
	TaskType string `protobuf:"bytes,5,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"` // "video_transcode", "image_process", "generic"
	// 视频转码专用字段
	InputUrl    string `protobuf:"bytes,10,opt,name=input_url,json=inputUrl,proto3" json:"input_url,omitempty"`           // 输入文件 URL 或路径
	OutputUrl   string `protobuf:"bytes,11,opt,name=output_url,json=outputUrl,proto3" json:"output_url,omitempty"`        // 输出文件 URL 或路径
	StartOffset int64  `protobuf:"varint,12,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"` // 起始偏移（帧号或字节偏移）
	Length      int64  `protobuf:"varint,13,opt,name=length,proto3" json:"length,omitempty"`                              // 长度（帧数或字节数）
	Codec       string `protobuf:"bytes,14,opt,name=codec,proto3" json:"codec,omitempty"`                                 // 目标编码器（如 "libx264", "libsvtav1"）
	Preset      string `protobuf:"bytes,15,opt,name=preset,proto3" json:"preset,omitempty"`                               // 编码预设（如 "fast", "medium"）
	Crf         int32  `protobuf:"varint,16,opt,name=crf,proto3" json:"crf,omitempty"`                                    // 质量参数
	ExtraArgs   string `protobuf:"bytes,17,opt,name=extra_args,json=extraArgs,proto3" json:"extra_args,omitempty"`        // 额外 FFmpeg 参数（JSON 格式）
	// 通用任务字段
	Payload  []byte            `protobuf:"bytes,20,opt,name=payload,proto3" json:"payload,omitempty"`                                                                             // 通用任务载荷
	Metadata map[string]string `protobuf:"bytes,21,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 自定义元数据
	// 优先级 & 超时
	Priority      int32 `protobuf:"varint,30,opt,name=priority,proto3" json:"priority,omitempty"`                    // 优先级（越大越高）
	TimeoutMs     int64 `protobuf:"varint,31,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"` // 任务超时（毫秒），0 表示不限
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskChunk) Reset() {
	*x = TaskChunk{}
	mi := &file_controller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskChunk) ProtoMessage() {}

func (x *TaskChunk) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskChunk.ProtoReflect.Descriptor instead.
func (*TaskChunk) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{2}
}

func (x *TaskChunk) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskChunk) GetParentTaskId() string {
	if x != nil {
		return x.ParentTaskId
	}
	return ""
}

func (x *TaskChunk) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *TaskChunk) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *TaskChunk) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *TaskChunk) GetInputUrl() string {
	if x != nil {
		return x.InputUrl
	}
	return ""
}

func (x *TaskChunk) GetOutputUrl() string {
	if x != nil {
		return x.OutputUrl
	}
	return ""
}

func (x *TaskChunk) GetStartOffset() int64 {
	if x != nil {
		return x.StartOffset
	}
	return 0
}

func (x *TaskChunk) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *TaskChunk) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *TaskChunk) GetPreset() string {
	if x != nil {
		return x.Preset
	}
	return ""
}

func (x *TaskChunk) GetCrf() int32 {
	if x != nil {
		return x.Crf
	}
	return 0
}

func (x *TaskChunk) GetExtraArgs() string {
	if x != nil {
		return x.ExtraArgs
	}
	return ""
}

func (x *TaskChunk) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TaskChunk) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TaskChunk) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *TaskChunk) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// 任务下发请求
type DispatchTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         *TaskChunk             `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchTaskRequest) Reset() {
	*x = DispatchTaskRequest{}
	mi := &file_controller_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchTaskRequest) ProtoMessage() {}

func (x *DispatchTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchTaskRequest.ProtoReflect.Descriptor instead.
func (*DispatchTaskRequest) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{3}
}

func (x *DispatchTaskRequest) GetChunk() *TaskChunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

// 任务下发响应
type DispatchTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`                // worker 是否接受该任务
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                     // 拒绝原因（accepted=false 时有值）
	WorkerId      string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"` // worker 自身 ID（确认身份）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchTaskResponse) Reset() {
	*x = DispatchTaskResponse{}
	mi := &file_controller_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchTaskResponse) ProtoMessage() {}

func (x *DispatchTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchTaskResponse.ProtoReflect.Descriptor instead.
func (*DispatchTaskResponse) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{4}
}

func (x *DispatchTaskResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *DispatchTaskResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DispatchTaskResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

// 取消任务请求
type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 要取消的任务 ID
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`               // 取消原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_controller_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{5}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CancelTaskRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 取消任务响应
type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 详细信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_controller_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{6}
}

func (x *CancelTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Ping 请求（controller 主动探活 worker）
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 发送时间戳（unix ms）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_controller_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{7}
}

func (x *PingRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Ping 响应
type PingResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RequestTimestamp   int64                  `protobuf:"varint,1,opt,name=request_timestamp,json=requestTimestamp,proto3" json:"request_timestamp,omitempty"`    // 回传请求时间戳
	ResponseTimestamp  int64                  `protobuf:"varint,2,opt,name=response_timestamp,json=responseTimestamp,proto3" json:"response_timestamp,omitempty"` // worker 响应时间戳
	WorkerId           string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	CurrentTaskCount   int32                  `protobuf:"varint,4,opt,name=current_task_count,json=currentTaskCount,proto3" json:"current_task_count,omitempty"`        // 当前正在执行的任务数
	CpuUsagePercent    float64                `protobuf:"fixed64,5,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`          // 当前 CPU 使用率
	MemoryUsagePercent float64                `protobuf:"fixed64,6,opt,name=memory_usage_percent,json=memoryUsagePercent,proto3" json:"memory_usage_percent,omitempty"` // 当前内存使用率
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_controller_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{8}
}

func (x *PingResponse) GetRequestTimestamp() int64 {
	if x != nil {
		return x.RequestTimestamp
	}
	return 0
}

func (x *PingResponse) GetResponseTimestamp() int64 {
	if x != nil {
		return x.ResponseTimestamp
	}
	return 0
}

func (x *PingResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *PingResponse) GetCurrentTaskCount() int32 {
	if x != nil {
		return x.CurrentTaskCount
	}
	return 0
}

func (x *PingResponse) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *PingResponse) GetMemoryUsagePercent() float64 {
	if x != nil {
		return x.MemoryUsagePercent
	}
	return 0
}

// 任务进度上报（worker → controller，通过此服务的流式或单次调用）
type TaskProgressReport struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TaskId   string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkerId string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// 进度
	ProgressPercent float64 `protobuf:"fixed64,3,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"` // [0, 100]
	ProcessedUnits  int64   `protobuf:"varint,4,opt,name=processed_units,json=processedUnits,proto3" json:"processed_units,omitempty"`     // 已处理单元数
	TotalUnits      int64   `protobuf:"varint,5,opt,name=total_units,json=totalUnits,proto3" json:"total_units,omitempty"`                 // 总单元数
	// 状态
	Status TaskStatus `protobuf:"varint,6,opt,name=status,proto3,enum=controller_2_worker_service.TaskStatus" json:"status,omitempty"`
	// 性能指标
	Fps        float64 `protobuf:"fixed64,10,opt,name=fps,proto3" json:"fps,omitempty"`                                 // 视频处理帧率
	SpeedRatio float64 `protobuf:"fixed64,11,opt,name=speed_ratio,json=speedRatio,proto3" json:"speed_ratio,omitempty"` // 处理速度比（1.0 = 实时）
	EtaMs      int64   `protobuf:"varint,12,opt,name=eta_ms,json=etaMs,proto3" json:"eta_ms,omitempty"`                 // 预计剩余时间（毫秒）
	// 错误信息
	ErrorMessage string `protobuf:"bytes,20,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// 时间戳
	Timestamp     int64 `protobuf:"varint,30,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskProgressReport) Reset() {
	*x = TaskProgressReport{}
	mi := &file_controller_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskProgressReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskProgressReport) ProtoMessage() {}

func (x *TaskProgressReport) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskProgressReport.ProtoReflect.Descriptor instead.
func (*TaskProgressReport) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{9}
}

func (x *TaskProgressReport) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskProgressReport) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskProgressReport) GetProgressPercent() float64 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *TaskProgressReport) GetProcessedUnits() int64 {
	if x != nil {
		return x.ProcessedUnits
	}
	return 0
}

func (x *TaskProgressReport) GetTotalUnits() int64 {
	if x != nil {
		return x.TotalUnits
	}
	return 0
}

func (x *TaskProgressReport) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNKNOWN
}

func (x *TaskProgressReport) GetFps() float64 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *TaskProgressReport) GetSpeedRatio() float64 {
	if x != nil {
		return x.SpeedRatio
	}
	return 0
}

func (x *TaskProgressReport) GetEtaMs() int64 {
	if x != nil {
		return x.EtaMs
	}
	return 0
}

func (x *TaskProgressReport) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskProgressReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 任务进度上报响应
type TaskProgressResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Received bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	// controller 可以通过此字段告知 worker 是否需要取消任务
	ShouldCancel  bool `protobuf:"varint,2,opt,name=should_cancel,json=shouldCancel,proto3" json:"should_cancel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskProgressResponse) Reset() {
	*x = TaskProgressResponse{}
	mi := &file_controller_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskProgressResponse) ProtoMessage() {}

func (x *TaskProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskProgressResponse.ProtoReflect.Descriptor instead.
func (*TaskProgressResponse) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{10}
}

func (x *TaskProgressResponse) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

func (x *TaskProgressResponse) GetShouldCancel() bool {
	if x != nil {
		return x.ShouldCancel
	}
	return false
}

// 查询 worker 当前任务列表
type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_controller_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{11}
}

type TaskInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskType        string                 `protobuf:"bytes,2,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Status          TaskStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=controller_2_worker_service.TaskStatus" json:"status,omitempty"`
	ProgressPercent float64                `protobuf:"fixed64,4,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	StartTime       int64                  `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // 任务开始执行时间（unix ms）
	ElapsedMs       int64                  `protobuf:"varint,6,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"` // 已耗时（毫秒）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskInfo) Reset() {
	*x = TaskInfo{}
	mi := &file_controller_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfo) ProtoMessage() {}

func (x *TaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfo.ProtoReflect.Descriptor instead.
func (*TaskInfo) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{12}
}

func (x *TaskInfo) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskInfo) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *TaskInfo) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNKNOWN
}

func (x *TaskInfo) GetProgressPercent() float64 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *TaskInfo) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *TaskInfo) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Tasks         []*TaskInfo            `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_controller_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{13}
}

func (x *ListTasksResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ListTasksResponse) GetTasks() []*TaskInfo {
	if x != nil {
		return x.Tasks
	}
	return nil
}

var File_controller_proto protoreflect.FileDescriptor

const file_controller_proto_rawDesc = "" +
	"\n" +
	"\x10controller.proto\x12\x1bcontroller_2_worker_service\"\x9e\x01\n" +
	"\x04Task\x12\x1b\n" +
	"\ttask_type\x18\x01 \x01(\x05R\btaskType\x12\x1d\n" +
	"\n" +
	"task_level\x18\x02 \x01(\x05R\ttaskLevel\x12#\n" +
	"\rtask_priority\x18\x03 \x01(\x05R\ftaskPriority\x12\x1b\n" +
	"\ttask_data\x18\x04 \x01(\fR\btaskData\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\"r\n" +
	"\x11TaskReportRequest\x12 \n" +
	"\ftask_port_id\x18\x01 \x01(\tR\n" +
	"taskPortId\x12;\n" +
	"\adetails\x18\x02 \x03(\v2!.controller_2_worker_service.TaskR\adetails\"\xe5\x04\n" +
	"\tTaskChunk\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12$\n" +
	"\x0eparent_task_id\x18\x02 \x01(\tR\fparentTaskId\x12\x1f\n" +
	"\vchunk_index\x18\x03 \x01(\x05R\n" +
	"chunkIndex\x12!\n" +
	"\ftotal_chunks\x18\x04 \x01(\x05R\vtotalChunks\x12\x1b\n" +
	"\ttask_type\x18\x05 \x01(\tR\btaskType\x12\x1b\n" +
	"\tinput_url\x18\n" +
	" \x01(\tR\binputUrl\x12\x1d\n" +
	"\n" +
	"output_url\x18\v \x01(\tR\toutputUrl\x12!\n" +
	"\fstart_offset\x18\f \x01(\x03R\vstartOffset\x12\x16\n" +
	"\x06length\x18\r \x01(\x03R\x06length\x12\x14\n" +
	"\x05codec\x18\x0e \x01(\tR\x05codec\x12\x16\n" +
	"\x06preset\x18\x0f \x01(\tR\x06preset\x12\x10\n" +
	"\x03crf\x18\x10 \x01(\x05R\x03crf\x12\x1d\n" +
	"\n" +
	"extra_args\x18\x11 \x01(\tR\textraArgs\x12\x18\n" +
	"\apayload\x18\x14 \x01(\fR\apayload\x12P\n" +
	"\bmetadata\x18\x15 \x03(\v24.controller_2_worker_service.TaskChunk.MetadataEntryR\bmetadata\x12\x1a\n" +
	"\bpriority\x18\x1e \x01(\x05R\bpriority\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x1f \x01(\x03R\ttimeoutMs\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"S\n" +
	"\x13DispatchTaskRequest\x12<\n" +
	"\x05chunk\x18\x01 \x01(\v2&.controller_2_worker_service.TaskChunkR\x05chunk\"g\n" +
	"\x14DispatchTaskResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\"D\n" +
	"\x11CancelTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"H\n" +
	"\x12CancelTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"+\n" +
	"\vPingRequest\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\x93\x02\n" +
	"\fPingResponse\x12+\n" +
	"\x11request_timestamp\x18\x01 \x01(\x03R\x10requestTimestamp\x12-\n" +
	"\x12response_timestamp\x18\x02 \x01(\x03R\x11responseTimestamp\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x12,\n" +
	"\x12current_task_count\x18\x04 \x01(\x05R\x10currentTaskCount\x12*\n" +
	"\x11cpu_usage_percent\x18\x05 \x01(\x01R\x0fcpuUsagePercent\x120\n" +
	"\x14memory_usage_percent\x18\x06 \x01(\x01R\x12memoryUsagePercent\"\x8d\x03\n" +
	"\x12TaskProgressReport\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12)\n" +
	"\x10progress_percent\x18\x03 \x01(\x01R\x0fprogressPercent\x12'\n" +
	"\x0fprocessed_units\x18\x04 \x01(\x03R\x0eprocessedUnits\x12\x1f\n" +
	"\vtotal_units\x18\x05 \x01(\x03R\n" +
	"totalUnits\x12?\n" +
	"\x06status\x18\x06 \x01(\x0e2'.controller_2_worker_service.TaskStatusR\x06status\x12\x10\n" +
	"\x03fps\x18\n" +
	" \x01(\x01R\x03fps\x12\x1f\n" +
	"\vspeed_ratio\x18\v \x01(\x01R\n" +
	"speedRatio\x12\x15\n" +
	"\x06eta_ms\x18\f \x01(\x03R\x05etaMs\x12#\n" +
	"\rerror_message\x18\x14 \x01(\tR\ferrorMessage\x12\x1c\n" +
	"\ttimestamp\x18\x1e \x01(\x03R\ttimestamp\"W\n" +
	"\x14TaskProgressResponse\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived\x12#\n" +
	"\rshould_cancel\x18\x02 \x01(\bR\fshouldCancel\"\x12\n" +
	"\x10ListTasksRequest\"\xea\x01\n" +
	"\bTaskInfo\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\ttask_type\x18\x02 \x01(\tR\btaskType\x12?\n" +
	"\x06status\x18\x03 \x01(\x0e2'.controller_2_worker_service.TaskStatusR\x06status\x12)\n" +
	"\x10progress_percent\x18\x04 \x01(\x01R\x0fprogressPercent\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\x03R\tstartTime\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\x06 \x01(\x03R\telapsedMs\"m\n" +
	"\x11ListTasksResponse\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12;\n" +
	"\x05tasks\x18\x02 \x03(\v2%.controller_2_worker_service.TaskInfoR\x05tasks*\xbe\x01\n" +
	"\n" +
	"TaskStatus\x12\x17\n" +
	"\x13TASK_STATUS_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13TASK_STATUS_PENDING\x10\x01\x12\x17\n" +
	"\x13TASK_STATUS_RUNNING\x10\x02\x12\x19\n" +
	"\x15TASK_STATUS_COMPLETED\x10\x03\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x04\x12\x19\n" +
	"\x15TASK_STATUS_CANCELLED\x10\x05\x12\x17\n" +
	"\x13TASK_STATUS_TIMEOUT\x10\x062\xb6\x04\n" +
	"\x11Controller2Worker\x12s\n" +
	"\fDispatchTask\x120.controller_2_worker_service.DispatchTaskRequest\x1a1.controller_2_worker_service.DispatchTaskResponse\x12m\n" +
	"\n" +
	"CancelTask\x12..controller_2_worker_service.CancelTaskRequest\x1a/.controller_2_worker_service.CancelTaskResponse\x12[\n" +
	"\x04Ping\x12(.controller_2_worker_service.PingRequest\x1a).controller_2_worker_service.PingResponse\x12t\n" +
	"\x0eReportProgress\x12/.controller_2_worker_service.TaskProgressReport\x1a1.controller_2_worker_service.TaskProgressResponse\x12j\n" +
	"\tListTasks\x12-.controller_2_worker_service.ListTasksRequest\x1a..controller_2_worker_service.ListTasksResponseB:Z8script/rpc_server/controller;controller_2_worker_serviceb\x06proto3"

var (
	file_controller_proto_rawDescOnce sync.Once
	file_controller_proto_rawDescData []byte
)

func file_controller_proto_rawDescGZIP() []byte {
	file_controller_proto_rawDescOnce.Do(func() {
		file_controller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controller_proto_rawDesc), len(file_controller_proto_rawDesc)))
	})
	return file_controller_proto_rawDescData
}

var file_controller_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_controller_proto_goTypes = []any{
	(TaskStatus)(0),              // 0: controller_2_worker_service.TaskStatus
	(*Task)(nil),                 // 1: controller_2_worker_service.Task
	(*TaskReportRequest)(nil),    // 2: controller_2_worker_service.TaskReportRequest
	(*TaskChunk)(nil),            // 3: controller_2_worker_service.TaskChunk
	(*DispatchTaskRequest)(nil),  // 4: controller_2_worker_service.DispatchTaskRequest
	(*DispatchTaskResponse)(nil), // 5: controller_2_worker_service.DispatchTaskResponse
	(*CancelTaskRequest)(nil),    // 6: controller_2_worker_service.CancelTaskRequest
	(*CancelTaskResponse)(nil),   // 7: controller_2_worker_service.CancelTaskResponse
	(*PingRequest)(nil),          // 8: controller_2_worker_service.PingRequest
	(*PingResponse)(nil),         // 9: controller_2_worker_service.PingResponse
	(*TaskProgressReport)(nil),   // 10: controller_2_worker_service.TaskProgressReport
	(*TaskProgressResponse)(nil), // 11: controller_2_worker_service.TaskProgressResponse
	(*ListTasksRequest)(nil),     // 12: controller_2_worker_service.ListTasksRequest
	(*TaskInfo)(nil),             // 13: controller_2_worker_service.TaskInfo
	(*ListTasksResponse)(nil),    // 14: controller_2_worker_service.ListTasksResponse
	nil,                          // 15: controller_2_worker_service.TaskChunk.MetadataEntry
}
var file_controller_proto_depIdxs = []int32{
	1,  // 0: controller_2_worker_service.TaskReportRequest.details:type_name -> controller_2_worker_service.Task
	15, // 1: controller_2_worker_service.TaskChunk.metadata:type_name -> controller_2_worker_service.TaskChunk.MetadataEntry
	3,  // 2: controller_2_worker_service.DispatchTaskRequest.chunk:type_name -> controller_2_worker_service.TaskChunk
	0,  // 3: controller_2_worker_service.TaskProgressReport.status:type_name -> controller_2_worker_service.TaskStatus
	0,  // 4: controller_2_worker_service.TaskInfo.status:type_name -> controller_2_worker_service.TaskStatus
	13, // 5: controller_2_worker_service.ListTasksResponse.tasks:type_name -> controller_2_worker_service.TaskInfo
	4,  // 6: controller_2_worker_service.Controller2Worker.DispatchTask:input_type -> controller_2_worker_service.DispatchTaskRequest
	6,  // 7: controller_2_worker_service.Controller2Worker.CancelTask:input_type -> controller_2_worker_service.CancelTaskRequest
	8,  // 8: controller_2_worker_service.Controller2Worker.Ping:input_type -> controller_2_worker_service.PingRequest
	10, // 9: controller_2_worker_service.Controller2Worker.ReportProgress:input_type -> controller_2_worker_service.TaskProgressReport
	12, // 10: controller_2_worker_service.Controller2Worker.ListTasks:input_type -> controller_2_worker_service.ListTasksRequest
	5,  // 11: controller_2_worker_service.Controller2Worker.DispatchTask:output_type -> controller_2_worker_service.DispatchTaskResponse
	7,  // 12: controller_2_worker_service.Controller2Worker.CancelTask:output_type -> controller_2_worker_service.CancelTaskResponse
	9,  // 13: controller_2_worker_service.Controller2Worker.Ping:output_type -> controller_2_worker_service.PingResponse
	11, // 14: controller_2_worker_service.Controller2Worker.ReportProgress:output_type -> controller_2_worker_service.TaskProgressResponse
	14, // 15: controller_2_worker_service.Controller2Worker.ListTasks:output_type -> controller_2_worker_service.ListTasksResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_controller_proto_init() }
func file_controller_proto_init() {
	if File_controller_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controller_proto_rawDesc), len(file_controller_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controller_proto_goTypes,
		DependencyIndexes: file_controller_proto_depIdxs,
		EnumInfos:         file_controller_proto_enumTypes,
		MessageInfos:      file_controller_proto_msgTypes,
	}.Build()
	File_controller_proto = out.File
	file_controller_proto_goTypes = nil
	file_controller_proto_depIdxs = nil
}
